// Code generated by mockery v2.53.5. DO NOT EDIT.

package fakelock

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// Deduplicator is an autogenerated mock type for the Deduplicator type
type Deduplicator struct {
	mock.Mock
}

type Deduplicator_Expecter struct {
	mock *mock.Mock
}

func (_m *Deduplicator) EXPECT() *Deduplicator_Expecter {
	return &Deduplicator_Expecter{mock: &_m.Mock}
}

// IsDuplicate provides a mock function with given fields: ctx, eventID
func (_m *Deduplicator) IsDuplicate(ctx context.Context, eventID string) (bool, error) {
	ret := _m.Called(ctx, eventID)

	if len(ret) == 0 {
		panic("no return value specified for IsDuplicate")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (bool, error)); ok {
		return rf(ctx, eventID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = rf(ctx, eventID)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, eventID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Deduplicator_IsDuplicate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsDuplicate'
type Deduplicator_IsDuplicate_Call struct {
	*mock.Call
}

// IsDuplicate is a helper method to define mock.On call
//   - ctx context.Context
//   - eventID string
func (_e *Deduplicator_Expecter) IsDuplicate(ctx interface{}, eventID interface{}) *Deduplicator_IsDuplicate_Call {
	return &Deduplicator_IsDuplicate_Call{Call: _e.mock.On("IsDuplicate", ctx, eventID)}
}

func (_c *Deduplicator_IsDuplicate_Call) Run(run func(ctx context.Context, eventID string)) *Deduplicator_IsDuplicate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *Deduplicator_IsDuplicate_Call) Return(_a0 bool, _a1 error) *Deduplicator_IsDuplicate_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Deduplicator_IsDuplicate_Call) RunAndReturn(run func(context.Context, string) (bool, error)) *Deduplicator_IsDuplicate_Call {
	_c.Call.Return(run)
	return _c
}

// NewDeduplicator creates a new instance of Deduplicator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDeduplicator(t interface {
	mock.TestingT
	Cleanup(func())
}) *Deduplicator {
	mock := &Deduplicator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
