// Code generated by mockery v2.53.5. DO NOT EDIT.

package fakelock

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// Locker is an autogenerated mock type for the Locker type
type Locker struct {
	mock.Mock
}

type Locker_Expecter struct {
	mock *mock.Mock
}

func (_m *Locker) EXPECT() *Locker_Expecter {
	return &Locker_Expecter{mock: &_m.Mock}
}

// Acquire provides a mock function with given fields: ctx, key
func (_m *Locker) Acquire(ctx context.Context, key string) (func(), bool, error) {
	ret := _m.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for Acquire")
	}

	var r0 func()
	var r1 bool
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (func(), bool, error)); ok {
		return rf(ctx, key)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) func()); ok {
		r0 = rf(ctx, key)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(func())
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) bool); ok {
		r1 = rf(ctx, key)
	} else {
		r1 = ret.Get(1).(bool)
	}

	if rf, ok := ret.Get(2).(func(context.Context, string) error); ok {
		r2 = rf(ctx, key)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// Locker_Acquire_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Acquire'
type Locker_Acquire_Call struct {
	*mock.Call
}

// Acquire is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
func (_e *Locker_Expecter) Acquire(ctx interface{}, key interface{}) *Locker_Acquire_Call {
	return &Locker_Acquire_Call{Call: _e.mock.On("Acquire", ctx, key)}
}

func (_c *Locker_Acquire_Call) Run(run func(ctx context.Context, key string)) *Locker_Acquire_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *Locker_Acquire_Call) Return(release func(), acquired bool, err error) *Locker_Acquire_Call {
	_c.Call.Return(release, acquired, err)
	return _c
}

func (_c *Locker_Acquire_Call) RunAndReturn(run func(context.Context, string) (func(), bool, error)) *Locker_Acquire_Call {
	_c.Call.Return(run)
	return _c
}

// NewLocker creates a new instance of Locker. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewLocker(t interface {
	mock.TestingT
	Cleanup(func())
}) *Locker {
	mock := &Locker{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
