// Code generated by mockery v2.53.5. DO NOT EDIT.

package fakeruntime

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	sql "database/sql"
)

// DBPool is an autogenerated mock type for the DBPool type
type DBPool struct {
	mock.Mock
}

type DBPool_Expecter struct {
	mock *mock.Mock
}

func (_m *DBPool) EXPECT() *DBPool_Expecter {
	return &DBPool_Expecter{mock: &_m.Mock}
}

// Close provides a mock function with no fields
func (_m *DBPool) Close() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DBPool_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type DBPool_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *DBPool_Expecter) Close() *DBPool_Close_Call {
	return &DBPool_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *DBPool_Close_Call) Run(run func()) *DBPool_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *DBPool_Close_Call) Return(_a0 error) *DBPool_Close_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *DBPool_Close_Call) RunAndReturn(run func() error) *DBPool_Close_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function with given fields: ctx, dsn
func (_m *DBPool) Get(ctx context.Context, dsn string) (*sql.DB, error) {
	ret := _m.Called(ctx, dsn)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *sql.DB
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*sql.DB, error)); ok {
		return rf(ctx, dsn)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *sql.DB); ok {
		r0 = rf(ctx, dsn)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sql.DB)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, dsn)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DBPool_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type DBPool_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - dsn string
func (_e *DBPool_Expecter) Get(ctx interface{}, dsn interface{}) *DBPool_Get_Call {
	return &DBPool_Get_Call{Call: _e.mock.On("Get", ctx, dsn)}
}

func (_c *DBPool_Get_Call) Run(run func(ctx context.Context, dsn string)) *DBPool_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *DBPool_Get_Call) Return(_a0 *sql.DB, _a1 error) *DBPool_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *DBPool_Get_Call) RunAndReturn(run func(context.Context, string) (*sql.DB, error)) *DBPool_Get_Call {
	_c.Call.Return(run)
	return _c
}

// NewDBPool creates a new instance of DBPool. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDBPool(t interface {
	mock.TestingT
	Cleanup(func())
}) *DBPool {
	mock := &DBPool{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
