// Code generated by mockery v2.53.5. DO NOT EDIT.

package fakeruntime

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	time "time"
)

// Locker is an autogenerated mock type for the Locker type
type Locker struct {
	mock.Mock
}

type Locker_Expecter struct {
	mock *mock.Mock
}

func (_m *Locker) EXPECT() *Locker_Expecter {
	return &Locker_Expecter{mock: &_m.Mock}
}

// Lock provides a mock function with given fields: ctx, key, timeout
func (_m *Locker) Lock(ctx context.Context, key string, timeout time.Duration) error {
	ret := _m.Called(ctx, key, timeout)

	if len(ret) == 0 {
		panic("no return value specified for Lock")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, time.Duration) error); ok {
		r0 = rf(ctx, key, timeout)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Locker_Lock_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Lock'
type Locker_Lock_Call struct {
	*mock.Call
}

// Lock is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
//   - timeout time.Duration
func (_e *Locker_Expecter) Lock(ctx interface{}, key interface{}, timeout interface{}) *Locker_Lock_Call {
	return &Locker_Lock_Call{Call: _e.mock.On("Lock", ctx, key, timeout)}
}

func (_c *Locker_Lock_Call) Run(run func(ctx context.Context, key string, timeout time.Duration)) *Locker_Lock_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(time.Duration))
	})
	return _c
}

func (_c *Locker_Lock_Call) Return(_a0 error) *Locker_Lock_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Locker_Lock_Call) RunAndReturn(run func(context.Context, string, time.Duration) error) *Locker_Lock_Call {
	_c.Call.Return(run)
	return _c
}

// Unlock provides a mock function with given fields: ctx, key
func (_m *Locker) Unlock(ctx context.Context, key string) error {
	ret := _m.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for Unlock")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, key)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Locker_Unlock_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Unlock'
type Locker_Unlock_Call struct {
	*mock.Call
}

// Unlock is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
func (_e *Locker_Expecter) Unlock(ctx interface{}, key interface{}) *Locker_Unlock_Call {
	return &Locker_Unlock_Call{Call: _e.mock.On("Unlock", ctx, key)}
}

func (_c *Locker_Unlock_Call) Run(run func(ctx context.Context, key string)) *Locker_Unlock_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *Locker_Unlock_Call) Return(_a0 error) *Locker_Unlock_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Locker_Unlock_Call) RunAndReturn(run func(context.Context, string) error) *Locker_Unlock_Call {
	_c.Call.Return(run)
	return _c
}

// NewLocker creates a new instance of Locker. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewLocker(t interface {
	mock.TestingT
	Cleanup(func())
}) *Locker {
	mock := &Locker{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
