// Code generated by mockery v2.53.5. DO NOT EDIT.

package fakeruntime

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	sql "database/sql"
)

// TxRegistry is an autogenerated mock type for the TxRegistry type
type TxRegistry struct {
	mock.Mock
}

type TxRegistry_Expecter struct {
	mock *mock.Mock
}

func (_m *TxRegistry) EXPECT() *TxRegistry_Expecter {
	return &TxRegistry_Expecter{mock: &_m.Mock}
}

// Begin provides a mock function with given fields: ctx, db, name
func (_m *TxRegistry) Begin(ctx context.Context, db *sql.DB, name string) (*sql.Tx, error) {
	ret := _m.Called(ctx, db, name)

	if len(ret) == 0 {
		panic("no return value specified for Begin")
	}

	var r0 *sql.Tx
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *sql.DB, string) (*sql.Tx, error)); ok {
		return rf(ctx, db, name)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *sql.DB, string) *sql.Tx); ok {
		r0 = rf(ctx, db, name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sql.Tx)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *sql.DB, string) error); ok {
		r1 = rf(ctx, db, name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TxRegistry_Begin_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Begin'
type TxRegistry_Begin_Call struct {
	*mock.Call
}

// Begin is a helper method to define mock.On call
//   - ctx context.Context
//   - db *sql.DB
//   - name string
func (_e *TxRegistry_Expecter) Begin(ctx interface{}, db interface{}, name interface{}) *TxRegistry_Begin_Call {
	return &TxRegistry_Begin_Call{Call: _e.mock.On("Begin", ctx, db, name)}
}

func (_c *TxRegistry_Begin_Call) Run(run func(ctx context.Context, db *sql.DB, name string)) *TxRegistry_Begin_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*sql.DB), args[2].(string))
	})
	return _c
}

func (_c *TxRegistry_Begin_Call) Return(_a0 *sql.Tx, _a1 error) *TxRegistry_Begin_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *TxRegistry_Begin_Call) RunAndReturn(run func(context.Context, *sql.DB, string) (*sql.Tx, error)) *TxRegistry_Begin_Call {
	_c.Call.Return(run)
	return _c
}

// Commit provides a mock function with given fields: name
func (_m *TxRegistry) Commit(name string) error {
	ret := _m.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for Commit")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(name)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// TxRegistry_Commit_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Commit'
type TxRegistry_Commit_Call struct {
	*mock.Call
}

// Commit is a helper method to define mock.On call
//   - name string
func (_e *TxRegistry_Expecter) Commit(name interface{}) *TxRegistry_Commit_Call {
	return &TxRegistry_Commit_Call{Call: _e.mock.On("Commit", name)}
}

func (_c *TxRegistry_Commit_Call) Run(run func(name string)) *TxRegistry_Commit_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *TxRegistry_Commit_Call) Return(_a0 error) *TxRegistry_Commit_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *TxRegistry_Commit_Call) RunAndReturn(run func(string) error) *TxRegistry_Commit_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function with given fields: name
func (_m *TxRegistry) Get(name string) (*sql.Tx, error) {
	ret := _m.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *sql.Tx
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*sql.Tx, error)); ok {
		return rf(name)
	}
	if rf, ok := ret.Get(0).(func(string) *sql.Tx); ok {
		r0 = rf(name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sql.Tx)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TxRegistry_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type TxRegistry_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - name string
func (_e *TxRegistry_Expecter) Get(name interface{}) *TxRegistry_Get_Call {
	return &TxRegistry_Get_Call{Call: _e.mock.On("Get", name)}
}

func (_c *TxRegistry_Get_Call) Run(run func(name string)) *TxRegistry_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *TxRegistry_Get_Call) Return(_a0 *sql.Tx, _a1 error) *TxRegistry_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *TxRegistry_Get_Call) RunAndReturn(run func(string) (*sql.Tx, error)) *TxRegistry_Get_Call {
	_c.Call.Return(run)
	return _c
}

// Rollback provides a mock function with given fields: name
func (_m *TxRegistry) Rollback(name string) error {
	ret := _m.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for Rollback")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(name)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// TxRegistry_Rollback_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Rollback'
type TxRegistry_Rollback_Call struct {
	*mock.Call
}

// Rollback is a helper method to define mock.On call
//   - name string
func (_e *TxRegistry_Expecter) Rollback(name interface{}) *TxRegistry_Rollback_Call {
	return &TxRegistry_Rollback_Call{Call: _e.mock.On("Rollback", name)}
}

func (_c *TxRegistry_Rollback_Call) Run(run func(name string)) *TxRegistry_Rollback_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *TxRegistry_Rollback_Call) Return(_a0 error) *TxRegistry_Rollback_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *TxRegistry_Rollback_Call) RunAndReturn(run func(string) error) *TxRegistry_Rollback_Call {
	_c.Call.Return(run)
	return _c
}

// RollbackAll provides a mock function with no fields
func (_m *TxRegistry) RollbackAll() {
	_m.Called()
}

// TxRegistry_RollbackAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RollbackAll'
type TxRegistry_RollbackAll_Call struct {
	*mock.Call
}

// RollbackAll is a helper method to define mock.On call
func (_e *TxRegistry_Expecter) RollbackAll() *TxRegistry_RollbackAll_Call {
	return &TxRegistry_RollbackAll_Call{Call: _e.mock.On("RollbackAll")}
}

func (_c *TxRegistry_RollbackAll_Call) Run(run func()) *TxRegistry_RollbackAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *TxRegistry_RollbackAll_Call) Return() *TxRegistry_RollbackAll_Call {
	_c.Call.Return()
	return _c
}

func (_c *TxRegistry_RollbackAll_Call) RunAndReturn(run func()) *TxRegistry_RollbackAll_Call {
	_c.Run(run)
	return _c
}

// NewTxRegistry creates a new instance of TxRegistry. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTxRegistry(t interface {
	mock.TestingT
	Cleanup(func())
}) *TxRegistry {
	mock := &TxRegistry{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
