// Code generated by mockery v2.53.6. DO NOT EDIT.

package fakestore

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	event "github.com/tailflowio/tailflow-shared/pkg/event"

	runtime "github.com/tailflow/tailflow/internal/runtime"

	store "github.com/tailflow/tailflow/internal/store"
)

// ExecutionStore is an autogenerated mock type for the ExecutionStore type
type ExecutionStore struct {
	mock.Mock
}

type ExecutionStore_Expecter struct {
	mock *mock.Mock
}

func (_m *ExecutionStore) EXPECT() *ExecutionStore_Expecter {
	return &ExecutionStore_Expecter{mock: &_m.Mock}
}

// Add provides a mock function with given fields: ctx, exec
func (_m *ExecutionStore) Add(ctx context.Context, exec *store.Execution) error {
	ret := _m.Called(ctx, exec)

	if len(ret) == 0 {
		panic("no return value specified for Add")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *store.Execution) error); ok {
		r0 = rf(ctx, exec)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ExecutionStore_Add_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Add'
type ExecutionStore_Add_Call struct {
	*mock.Call
}

// Add is a helper method to define mock.On call
//   - ctx context.Context
//   - exec *store.Execution
func (_e *ExecutionStore_Expecter) Add(ctx interface{}, exec interface{}) *ExecutionStore_Add_Call {
	return &ExecutionStore_Add_Call{Call: _e.mock.On("Add", ctx, exec)}
}

func (_c *ExecutionStore_Add_Call) Run(run func(ctx context.Context, exec *store.Execution)) *ExecutionStore_Add_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*store.Execution))
	})
	return _c
}

func (_c *ExecutionStore_Add_Call) Return(_a0 error) *ExecutionStore_Add_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ExecutionStore_Add_Call) RunAndReturn(run func(context.Context, *store.Execution) error) *ExecutionStore_Add_Call {
	_c.Call.Return(run)
	return _c
}

// AppendEvent provides a mock function with given fields: ctx, executionID, ev
func (_m *ExecutionStore) AppendEvent(ctx context.Context, executionID string, ev event.Event) error {
	ret := _m.Called(ctx, executionID, ev)

	if len(ret) == 0 {
		panic("no return value specified for AppendEvent")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, event.Event) error); ok {
		r0 = rf(ctx, executionID, ev)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ExecutionStore_AppendEvent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AppendEvent'
type ExecutionStore_AppendEvent_Call struct {
	*mock.Call
}

// AppendEvent is a helper method to define mock.On call
//   - ctx context.Context
//   - executionID string
//   - ev event.Event
func (_e *ExecutionStore_Expecter) AppendEvent(ctx interface{}, executionID interface{}, ev interface{}) *ExecutionStore_AppendEvent_Call {
	return &ExecutionStore_AppendEvent_Call{Call: _e.mock.On("AppendEvent", ctx, executionID, ev)}
}

func (_c *ExecutionStore_AppendEvent_Call) Run(run func(ctx context.Context, executionID string, ev event.Event)) *ExecutionStore_AppendEvent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(event.Event))
	})
	return _c
}

func (_c *ExecutionStore_AppendEvent_Call) Return(_a0 error) *ExecutionStore_AppendEvent_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ExecutionStore_AppendEvent_Call) RunAndReturn(run func(context.Context, string, event.Event) error) *ExecutionStore_AppendEvent_Call {
	_c.Call.Return(run)
	return _c
}

// Count provides a mock function with given fields: ctx
func (_m *ExecutionStore) Count(ctx context.Context) (int, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Count")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (int, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) int); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ExecutionStore_Count_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Count'
type ExecutionStore_Count_Call struct {
	*mock.Call
}

// Count is a helper method to define mock.On call
//   - ctx context.Context
func (_e *ExecutionStore_Expecter) Count(ctx interface{}) *ExecutionStore_Count_Call {
	return &ExecutionStore_Count_Call{Call: _e.mock.On("Count", ctx)}
}

func (_c *ExecutionStore_Count_Call) Run(run func(ctx context.Context)) *ExecutionStore_Count_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *ExecutionStore_Count_Call) Return(_a0 int, _a1 error) *ExecutionStore_Count_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ExecutionStore_Count_Call) RunAndReturn(run func(context.Context) (int, error)) *ExecutionStore_Count_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function with given fields: ctx, id
func (_m *ExecutionStore) Get(ctx context.Context, id string) (*store.Execution, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *store.Execution
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*store.Execution, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *store.Execution); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*store.Execution)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ExecutionStore_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type ExecutionStore_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *ExecutionStore_Expecter) Get(ctx interface{}, id interface{}) *ExecutionStore_Get_Call {
	return &ExecutionStore_Get_Call{Call: _e.mock.On("Get", ctx, id)}
}

func (_c *ExecutionStore_Get_Call) Run(run func(ctx context.Context, id string)) *ExecutionStore_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *ExecutionStore_Get_Call) Return(_a0 *store.Execution, _a1 error) *ExecutionStore_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ExecutionStore_Get_Call) RunAndReturn(run func(context.Context, string) (*store.Execution, error)) *ExecutionStore_Get_Call {
	_c.Call.Return(run)
	return _c
}

// GetAllStepMetrics provides a mock function with given fields: ctx
func (_m *ExecutionStore) GetAllStepMetrics(ctx context.Context) (map[string]*store.StepMetrics, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetAllStepMetrics")
	}

	var r0 map[string]*store.StepMetrics
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (map[string]*store.StepMetrics, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) map[string]*store.StepMetrics); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]*store.StepMetrics)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ExecutionStore_GetAllStepMetrics_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllStepMetrics'
type ExecutionStore_GetAllStepMetrics_Call struct {
	*mock.Call
}

// GetAllStepMetrics is a helper method to define mock.On call
//   - ctx context.Context
func (_e *ExecutionStore_Expecter) GetAllStepMetrics(ctx interface{}) *ExecutionStore_GetAllStepMetrics_Call {
	return &ExecutionStore_GetAllStepMetrics_Call{Call: _e.mock.On("GetAllStepMetrics", ctx)}
}

func (_c *ExecutionStore_GetAllStepMetrics_Call) Run(run func(ctx context.Context)) *ExecutionStore_GetAllStepMetrics_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *ExecutionStore_GetAllStepMetrics_Call) Return(_a0 map[string]*store.StepMetrics, _a1 error) *ExecutionStore_GetAllStepMetrics_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ExecutionStore_GetAllStepMetrics_Call) RunAndReturn(run func(context.Context) (map[string]*store.StepMetrics, error)) *ExecutionStore_GetAllStepMetrics_Call {
	_c.Call.Return(run)
	return _c
}

// GetEvents provides a mock function with given fields: ctx, executionID
func (_m *ExecutionStore) GetEvents(ctx context.Context, executionID string) ([]event.Event, error) {
	ret := _m.Called(ctx, executionID)

	if len(ret) == 0 {
		panic("no return value specified for GetEvents")
	}

	var r0 []event.Event
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]event.Event, error)); ok {
		return rf(ctx, executionID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []event.Event); ok {
		r0 = rf(ctx, executionID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]event.Event)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, executionID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ExecutionStore_GetEvents_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetEvents'
type ExecutionStore_GetEvents_Call struct {
	*mock.Call
}

// GetEvents is a helper method to define mock.On call
//   - ctx context.Context
//   - executionID string
func (_e *ExecutionStore_Expecter) GetEvents(ctx interface{}, executionID interface{}) *ExecutionStore_GetEvents_Call {
	return &ExecutionStore_GetEvents_Call{Call: _e.mock.On("GetEvents", ctx, executionID)}
}

func (_c *ExecutionStore_GetEvents_Call) Run(run func(ctx context.Context, executionID string)) *ExecutionStore_GetEvents_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *ExecutionStore_GetEvents_Call) Return(_a0 []event.Event, _a1 error) *ExecutionStore_GetEvents_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ExecutionStore_GetEvents_Call) RunAndReturn(run func(context.Context, string) ([]event.Event, error)) *ExecutionStore_GetEvents_Call {
	_c.Call.Return(run)
	return _c
}

// GetEventsPaginated provides a mock function with given fields: ctx, executionID, offset, limit
func (_m *ExecutionStore) GetEventsPaginated(ctx context.Context, executionID string, offset int, limit int) ([]event.Event, int, error) {
	ret := _m.Called(ctx, executionID, offset, limit)

	if len(ret) == 0 {
		panic("no return value specified for GetEventsPaginated")
	}

	var r0 []event.Event
	var r1 int
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int, int) ([]event.Event, int, error)); ok {
		return rf(ctx, executionID, offset, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, int, int) []event.Event); ok {
		r0 = rf(ctx, executionID, offset, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]event.Event)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, int, int) int); ok {
		r1 = rf(ctx, executionID, offset, limit)
	} else {
		r1 = ret.Get(1).(int)
	}

	if rf, ok := ret.Get(2).(func(context.Context, string, int, int) error); ok {
		r2 = rf(ctx, executionID, offset, limit)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// ExecutionStore_GetEventsPaginated_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetEventsPaginated'
type ExecutionStore_GetEventsPaginated_Call struct {
	*mock.Call
}

// GetEventsPaginated is a helper method to define mock.On call
//   - ctx context.Context
//   - executionID string
//   - offset int
//   - limit int
func (_e *ExecutionStore_Expecter) GetEventsPaginated(ctx interface{}, executionID interface{}, offset interface{}, limit interface{}) *ExecutionStore_GetEventsPaginated_Call {
	return &ExecutionStore_GetEventsPaginated_Call{Call: _e.mock.On("GetEventsPaginated", ctx, executionID, offset, limit)}
}

func (_c *ExecutionStore_GetEventsPaginated_Call) Run(run func(ctx context.Context, executionID string, offset int, limit int)) *ExecutionStore_GetEventsPaginated_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(int), args[3].(int))
	})
	return _c
}

func (_c *ExecutionStore_GetEventsPaginated_Call) Return(_a0 []event.Event, _a1 int, _a2 error) *ExecutionStore_GetEventsPaginated_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *ExecutionStore_GetEventsPaginated_Call) RunAndReturn(run func(context.Context, string, int, int) ([]event.Event, int, error)) *ExecutionStore_GetEventsPaginated_Call {
	_c.Call.Return(run)
	return _c
}

// GetStepMetrics provides a mock function with given fields: ctx, stepID
func (_m *ExecutionStore) GetStepMetrics(ctx context.Context, stepID string) (*store.StepMetrics, error) {
	ret := _m.Called(ctx, stepID)

	if len(ret) == 0 {
		panic("no return value specified for GetStepMetrics")
	}

	var r0 *store.StepMetrics
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*store.StepMetrics, error)); ok {
		return rf(ctx, stepID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *store.StepMetrics); ok {
		r0 = rf(ctx, stepID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*store.StepMetrics)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, stepID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ExecutionStore_GetStepMetrics_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetStepMetrics'
type ExecutionStore_GetStepMetrics_Call struct {
	*mock.Call
}

// GetStepMetrics is a helper method to define mock.On call
//   - ctx context.Context
//   - stepID string
func (_e *ExecutionStore_Expecter) GetStepMetrics(ctx interface{}, stepID interface{}) *ExecutionStore_GetStepMetrics_Call {
	return &ExecutionStore_GetStepMetrics_Call{Call: _e.mock.On("GetStepMetrics", ctx, stepID)}
}

func (_c *ExecutionStore_GetStepMetrics_Call) Run(run func(ctx context.Context, stepID string)) *ExecutionStore_GetStepMetrics_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *ExecutionStore_GetStepMetrics_Call) Return(_a0 *store.StepMetrics, _a1 error) *ExecutionStore_GetStepMetrics_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ExecutionStore_GetStepMetrics_Call) RunAndReturn(run func(context.Context, string) (*store.StepMetrics, error)) *ExecutionStore_GetStepMetrics_Call {
	_c.Call.Return(run)
	return _c
}

// IncrStepExecCount provides a mock function with given fields: ctx, stepID
func (_m *ExecutionStore) IncrStepExecCount(ctx context.Context, stepID string) error {
	ret := _m.Called(ctx, stepID)

	if len(ret) == 0 {
		panic("no return value specified for IncrStepExecCount")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, stepID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ExecutionStore_IncrStepExecCount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IncrStepExecCount'
type ExecutionStore_IncrStepExecCount_Call struct {
	*mock.Call
}

// IncrStepExecCount is a helper method to define mock.On call
//   - ctx context.Context
//   - stepID string
func (_e *ExecutionStore_Expecter) IncrStepExecCount(ctx interface{}, stepID interface{}) *ExecutionStore_IncrStepExecCount_Call {
	return &ExecutionStore_IncrStepExecCount_Call{Call: _e.mock.On("IncrStepExecCount", ctx, stepID)}
}

func (_c *ExecutionStore_IncrStepExecCount_Call) Run(run func(ctx context.Context, stepID string)) *ExecutionStore_IncrStepExecCount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *ExecutionStore_IncrStepExecCount_Call) Return(_a0 error) *ExecutionStore_IncrStepExecCount_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ExecutionStore_IncrStepExecCount_Call) RunAndReturn(run func(context.Context, string) error) *ExecutionStore_IncrStepExecCount_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx
func (_m *ExecutionStore) List(ctx context.Context) ([]*store.Execution, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []*store.Execution
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]*store.Execution, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []*store.Execution); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*store.Execution)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ExecutionStore_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type ExecutionStore_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
func (_e *ExecutionStore_Expecter) List(ctx interface{}) *ExecutionStore_List_Call {
	return &ExecutionStore_List_Call{Call: _e.mock.On("List", ctx)}
}

func (_c *ExecutionStore_List_Call) Run(run func(ctx context.Context)) *ExecutionStore_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *ExecutionStore_List_Call) Return(_a0 []*store.Execution, _a1 error) *ExecutionStore_List_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ExecutionStore_List_Call) RunAndReturn(run func(context.Context) ([]*store.Execution, error)) *ExecutionStore_List_Call {
	_c.Call.Return(run)
	return _c
}

// StepExecCounts provides a mock function with given fields: ctx
func (_m *ExecutionStore) StepExecCounts(ctx context.Context) (map[string]int, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for StepExecCounts")
	}

	var r0 map[string]int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (map[string]int, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) map[string]int); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]int)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ExecutionStore_StepExecCounts_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StepExecCounts'
type ExecutionStore_StepExecCounts_Call struct {
	*mock.Call
}

// StepExecCounts is a helper method to define mock.On call
//   - ctx context.Context
func (_e *ExecutionStore_Expecter) StepExecCounts(ctx interface{}) *ExecutionStore_StepExecCounts_Call {
	return &ExecutionStore_StepExecCounts_Call{Call: _e.mock.On("StepExecCounts", ctx)}
}

func (_c *ExecutionStore_StepExecCounts_Call) Run(run func(ctx context.Context)) *ExecutionStore_StepExecCounts_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *ExecutionStore_StepExecCounts_Call) Return(_a0 map[string]int, _a1 error) *ExecutionStore_StepExecCounts_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ExecutionStore_StepExecCounts_Call) RunAndReturn(run func(context.Context) (map[string]int, error)) *ExecutionStore_StepExecCounts_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, exec
func (_m *ExecutionStore) Update(ctx context.Context, exec *store.Execution) error {
	ret := _m.Called(ctx, exec)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *store.Execution) error); ok {
		r0 = rf(ctx, exec)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ExecutionStore_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type ExecutionStore_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - exec *store.Execution
func (_e *ExecutionStore_Expecter) Update(ctx interface{}, exec interface{}) *ExecutionStore_Update_Call {
	return &ExecutionStore_Update_Call{Call: _e.mock.On("Update", ctx, exec)}
}

func (_c *ExecutionStore_Update_Call) Run(run func(ctx context.Context, exec *store.Execution)) *ExecutionStore_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*store.Execution))
	})
	return _c
}

func (_c *ExecutionStore_Update_Call) Return(_a0 error) *ExecutionStore_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ExecutionStore_Update_Call) RunAndReturn(run func(context.Context, *store.Execution) error) *ExecutionStore_Update_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateExecution provides a mock function with given fields: ctx, id, fn
func (_m *ExecutionStore) UpdateExecution(ctx context.Context, id string, fn func(*store.Execution)) error {
	ret := _m.Called(ctx, id, fn)

	if len(ret) == 0 {
		panic("no return value specified for UpdateExecution")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, func(*store.Execution)) error); ok {
		r0 = rf(ctx, id, fn)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ExecutionStore_UpdateExecution_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateExecution'
type ExecutionStore_UpdateExecution_Call struct {
	*mock.Call
}

// UpdateExecution is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - fn func(*store.Execution)
func (_e *ExecutionStore_Expecter) UpdateExecution(ctx interface{}, id interface{}, fn interface{}) *ExecutionStore_UpdateExecution_Call {
	return &ExecutionStore_UpdateExecution_Call{Call: _e.mock.On("UpdateExecution", ctx, id, fn)}
}

func (_c *ExecutionStore_UpdateExecution_Call) Run(run func(ctx context.Context, id string, fn func(*store.Execution))) *ExecutionStore_UpdateExecution_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(func(*store.Execution)))
	})
	return _c
}

func (_c *ExecutionStore_UpdateExecution_Call) Return(_a0 error) *ExecutionStore_UpdateExecution_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ExecutionStore_UpdateExecution_Call) RunAndReturn(run func(context.Context, string, func(*store.Execution)) error) *ExecutionStore_UpdateExecution_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateStep provides a mock function with given fields: ctx, executionID, stepID, fn
func (_m *ExecutionStore) UpdateStep(ctx context.Context, executionID string, stepID string, fn func(*runtime.StepResult)) error {
	ret := _m.Called(ctx, executionID, stepID, fn)

	if len(ret) == 0 {
		panic("no return value specified for UpdateStep")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, func(*runtime.StepResult)) error); ok {
		r0 = rf(ctx, executionID, stepID, fn)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ExecutionStore_UpdateStep_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateStep'
type ExecutionStore_UpdateStep_Call struct {
	*mock.Call
}

// UpdateStep is a helper method to define mock.On call
//   - ctx context.Context
//   - executionID string
//   - stepID string
//   - fn func(*runtime.StepResult)
func (_e *ExecutionStore_Expecter) UpdateStep(ctx interface{}, executionID interface{}, stepID interface{}, fn interface{}) *ExecutionStore_UpdateStep_Call {
	return &ExecutionStore_UpdateStep_Call{Call: _e.mock.On("UpdateStep", ctx, executionID, stepID, fn)}
}

func (_c *ExecutionStore_UpdateStep_Call) Run(run func(ctx context.Context, executionID string, stepID string, fn func(*runtime.StepResult))) *ExecutionStore_UpdateStep_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(func(*runtime.StepResult)))
	})
	return _c
}

func (_c *ExecutionStore_UpdateStep_Call) Return(_a0 error) *ExecutionStore_UpdateStep_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ExecutionStore_UpdateStep_Call) RunAndReturn(run func(context.Context, string, string, func(*runtime.StepResult)) error) *ExecutionStore_UpdateStep_Call {
	_c.Call.Return(run)
	return _c
}

// NewExecutionStore creates a new instance of ExecutionStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewExecutionStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *ExecutionStore {
	mock := &ExecutionStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
