// Code generated by mockery v2.53.5. DO NOT EDIT.

package fakestore

import (
	mock "github.com/stretchr/testify/mock"
	event "github.com/tailflow/tailflow/internal/event"

	runtime "github.com/tailflow/tailflow/internal/runtime"

	store "github.com/tailflow/tailflow/internal/store"
)

// ExecutionStore is an autogenerated mock type for the ExecutionStore type
type ExecutionStore struct {
	mock.Mock
}

type ExecutionStore_Expecter struct {
	mock *mock.Mock
}

func (_m *ExecutionStore) EXPECT() *ExecutionStore_Expecter {
	return &ExecutionStore_Expecter{mock: &_m.Mock}
}

// Add provides a mock function with given fields: exec
func (_m *ExecutionStore) Add(exec *store.Execution) {
	_m.Called(exec)
}

// ExecutionStore_Add_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Add'
type ExecutionStore_Add_Call struct {
	*mock.Call
}

// Add is a helper method to define mock.On call
//   - exec *store.Execution
func (_e *ExecutionStore_Expecter) Add(exec interface{}) *ExecutionStore_Add_Call {
	return &ExecutionStore_Add_Call{Call: _e.mock.On("Add", exec)}
}

func (_c *ExecutionStore_Add_Call) Run(run func(exec *store.Execution)) *ExecutionStore_Add_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*store.Execution))
	})
	return _c
}

func (_c *ExecutionStore_Add_Call) Return() *ExecutionStore_Add_Call {
	_c.Call.Return()
	return _c
}

func (_c *ExecutionStore_Add_Call) RunAndReturn(run func(*store.Execution)) *ExecutionStore_Add_Call {
	_c.Run(run)
	return _c
}

// AppendEvent provides a mock function with given fields: executionID, ev
func (_m *ExecutionStore) AppendEvent(executionID string, ev event.Event) {
	_m.Called(executionID, ev)
}

// ExecutionStore_AppendEvent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AppendEvent'
type ExecutionStore_AppendEvent_Call struct {
	*mock.Call
}

// AppendEvent is a helper method to define mock.On call
//   - executionID string
//   - ev event.Event
func (_e *ExecutionStore_Expecter) AppendEvent(executionID interface{}, ev interface{}) *ExecutionStore_AppendEvent_Call {
	return &ExecutionStore_AppendEvent_Call{Call: _e.mock.On("AppendEvent", executionID, ev)}
}

func (_c *ExecutionStore_AppendEvent_Call) Run(run func(executionID string, ev event.Event)) *ExecutionStore_AppendEvent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(event.Event))
	})
	return _c
}

func (_c *ExecutionStore_AppendEvent_Call) Return() *ExecutionStore_AppendEvent_Call {
	_c.Call.Return()
	return _c
}

func (_c *ExecutionStore_AppendEvent_Call) RunAndReturn(run func(string, event.Event)) *ExecutionStore_AppendEvent_Call {
	_c.Run(run)
	return _c
}

// Count provides a mock function with no fields
func (_m *ExecutionStore) Count() int {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Count")
	}

	var r0 int
	if rf, ok := ret.Get(0).(func() int); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(int)
	}

	return r0
}

// ExecutionStore_Count_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Count'
type ExecutionStore_Count_Call struct {
	*mock.Call
}

// Count is a helper method to define mock.On call
func (_e *ExecutionStore_Expecter) Count() *ExecutionStore_Count_Call {
	return &ExecutionStore_Count_Call{Call: _e.mock.On("Count")}
}

func (_c *ExecutionStore_Count_Call) Run(run func()) *ExecutionStore_Count_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ExecutionStore_Count_Call) Return(_a0 int) *ExecutionStore_Count_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ExecutionStore_Count_Call) RunAndReturn(run func() int) *ExecutionStore_Count_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function with given fields: id
func (_m *ExecutionStore) Get(id string) (*store.Execution, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *store.Execution
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*store.Execution, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(string) *store.Execution); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*store.Execution)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ExecutionStore_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type ExecutionStore_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - id string
func (_e *ExecutionStore_Expecter) Get(id interface{}) *ExecutionStore_Get_Call {
	return &ExecutionStore_Get_Call{Call: _e.mock.On("Get", id)}
}

func (_c *ExecutionStore_Get_Call) Run(run func(id string)) *ExecutionStore_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *ExecutionStore_Get_Call) Return(_a0 *store.Execution, _a1 error) *ExecutionStore_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ExecutionStore_Get_Call) RunAndReturn(run func(string) (*store.Execution, error)) *ExecutionStore_Get_Call {
	_c.Call.Return(run)
	return _c
}

// GetAllStepMetrics provides a mock function with no fields
func (_m *ExecutionStore) GetAllStepMetrics() map[string]*store.StepMetrics {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetAllStepMetrics")
	}

	var r0 map[string]*store.StepMetrics
	if rf, ok := ret.Get(0).(func() map[string]*store.StepMetrics); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]*store.StepMetrics)
		}
	}

	return r0
}

// ExecutionStore_GetAllStepMetrics_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllStepMetrics'
type ExecutionStore_GetAllStepMetrics_Call struct {
	*mock.Call
}

// GetAllStepMetrics is a helper method to define mock.On call
func (_e *ExecutionStore_Expecter) GetAllStepMetrics() *ExecutionStore_GetAllStepMetrics_Call {
	return &ExecutionStore_GetAllStepMetrics_Call{Call: _e.mock.On("GetAllStepMetrics")}
}

func (_c *ExecutionStore_GetAllStepMetrics_Call) Run(run func()) *ExecutionStore_GetAllStepMetrics_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ExecutionStore_GetAllStepMetrics_Call) Return(_a0 map[string]*store.StepMetrics) *ExecutionStore_GetAllStepMetrics_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ExecutionStore_GetAllStepMetrics_Call) RunAndReturn(run func() map[string]*store.StepMetrics) *ExecutionStore_GetAllStepMetrics_Call {
	_c.Call.Return(run)
	return _c
}

// GetEvents provides a mock function with given fields: executionID
func (_m *ExecutionStore) GetEvents(executionID string) []event.Event {
	ret := _m.Called(executionID)

	if len(ret) == 0 {
		panic("no return value specified for GetEvents")
	}

	var r0 []event.Event
	if rf, ok := ret.Get(0).(func(string) []event.Event); ok {
		r0 = rf(executionID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]event.Event)
		}
	}

	return r0
}

// ExecutionStore_GetEvents_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetEvents'
type ExecutionStore_GetEvents_Call struct {
	*mock.Call
}

// GetEvents is a helper method to define mock.On call
//   - executionID string
func (_e *ExecutionStore_Expecter) GetEvents(executionID interface{}) *ExecutionStore_GetEvents_Call {
	return &ExecutionStore_GetEvents_Call{Call: _e.mock.On("GetEvents", executionID)}
}

func (_c *ExecutionStore_GetEvents_Call) Run(run func(executionID string)) *ExecutionStore_GetEvents_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *ExecutionStore_GetEvents_Call) Return(_a0 []event.Event) *ExecutionStore_GetEvents_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ExecutionStore_GetEvents_Call) RunAndReturn(run func(string) []event.Event) *ExecutionStore_GetEvents_Call {
	_c.Call.Return(run)
	return _c
}

// GetStepMetrics provides a mock function with given fields: stepID
func (_m *ExecutionStore) GetStepMetrics(stepID string) *store.StepMetrics {
	ret := _m.Called(stepID)

	if len(ret) == 0 {
		panic("no return value specified for GetStepMetrics")
	}

	var r0 *store.StepMetrics
	if rf, ok := ret.Get(0).(func(string) *store.StepMetrics); ok {
		r0 = rf(stepID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*store.StepMetrics)
		}
	}

	return r0
}

// ExecutionStore_GetStepMetrics_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetStepMetrics'
type ExecutionStore_GetStepMetrics_Call struct {
	*mock.Call
}

// GetStepMetrics is a helper method to define mock.On call
//   - stepID string
func (_e *ExecutionStore_Expecter) GetStepMetrics(stepID interface{}) *ExecutionStore_GetStepMetrics_Call {
	return &ExecutionStore_GetStepMetrics_Call{Call: _e.mock.On("GetStepMetrics", stepID)}
}

func (_c *ExecutionStore_GetStepMetrics_Call) Run(run func(stepID string)) *ExecutionStore_GetStepMetrics_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *ExecutionStore_GetStepMetrics_Call) Return(_a0 *store.StepMetrics) *ExecutionStore_GetStepMetrics_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ExecutionStore_GetStepMetrics_Call) RunAndReturn(run func(string) *store.StepMetrics) *ExecutionStore_GetStepMetrics_Call {
	_c.Call.Return(run)
	return _c
}

// IncrStepExecCount provides a mock function with given fields: stepID
func (_m *ExecutionStore) IncrStepExecCount(stepID string) {
	_m.Called(stepID)
}

// ExecutionStore_IncrStepExecCount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IncrStepExecCount'
type ExecutionStore_IncrStepExecCount_Call struct {
	*mock.Call
}

// IncrStepExecCount is a helper method to define mock.On call
//   - stepID string
func (_e *ExecutionStore_Expecter) IncrStepExecCount(stepID interface{}) *ExecutionStore_IncrStepExecCount_Call {
	return &ExecutionStore_IncrStepExecCount_Call{Call: _e.mock.On("IncrStepExecCount", stepID)}
}

func (_c *ExecutionStore_IncrStepExecCount_Call) Run(run func(stepID string)) *ExecutionStore_IncrStepExecCount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *ExecutionStore_IncrStepExecCount_Call) Return() *ExecutionStore_IncrStepExecCount_Call {
	_c.Call.Return()
	return _c
}

func (_c *ExecutionStore_IncrStepExecCount_Call) RunAndReturn(run func(string)) *ExecutionStore_IncrStepExecCount_Call {
	_c.Run(run)
	return _c
}

// List provides a mock function with no fields
func (_m *ExecutionStore) List() []*store.Execution {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []*store.Execution
	if rf, ok := ret.Get(0).(func() []*store.Execution); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*store.Execution)
		}
	}

	return r0
}

// ExecutionStore_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type ExecutionStore_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
func (_e *ExecutionStore_Expecter) List() *ExecutionStore_List_Call {
	return &ExecutionStore_List_Call{Call: _e.mock.On("List")}
}

func (_c *ExecutionStore_List_Call) Run(run func()) *ExecutionStore_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ExecutionStore_List_Call) Return(_a0 []*store.Execution) *ExecutionStore_List_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ExecutionStore_List_Call) RunAndReturn(run func() []*store.Execution) *ExecutionStore_List_Call {
	_c.Call.Return(run)
	return _c
}

// RefreshStepMetrics provides a mock function with no fields
func (_m *ExecutionStore) RefreshStepMetrics() {
	_m.Called()
}

// ExecutionStore_RefreshStepMetrics_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RefreshStepMetrics'
type ExecutionStore_RefreshStepMetrics_Call struct {
	*mock.Call
}

// RefreshStepMetrics is a helper method to define mock.On call
func (_e *ExecutionStore_Expecter) RefreshStepMetrics() *ExecutionStore_RefreshStepMetrics_Call {
	return &ExecutionStore_RefreshStepMetrics_Call{Call: _e.mock.On("RefreshStepMetrics")}
}

func (_c *ExecutionStore_RefreshStepMetrics_Call) Run(run func()) *ExecutionStore_RefreshStepMetrics_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ExecutionStore_RefreshStepMetrics_Call) Return() *ExecutionStore_RefreshStepMetrics_Call {
	_c.Call.Return()
	return _c
}

func (_c *ExecutionStore_RefreshStepMetrics_Call) RunAndReturn(run func()) *ExecutionStore_RefreshStepMetrics_Call {
	_c.Run(run)
	return _c
}

// StepExecCounts provides a mock function with no fields
func (_m *ExecutionStore) StepExecCounts() map[string]int {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for StepExecCounts")
	}

	var r0 map[string]int
	if rf, ok := ret.Get(0).(func() map[string]int); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]int)
		}
	}

	return r0
}

// ExecutionStore_StepExecCounts_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StepExecCounts'
type ExecutionStore_StepExecCounts_Call struct {
	*mock.Call
}

// StepExecCounts is a helper method to define mock.On call
func (_e *ExecutionStore_Expecter) StepExecCounts() *ExecutionStore_StepExecCounts_Call {
	return &ExecutionStore_StepExecCounts_Call{Call: _e.mock.On("StepExecCounts")}
}

func (_c *ExecutionStore_StepExecCounts_Call) Run(run func()) *ExecutionStore_StepExecCounts_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ExecutionStore_StepExecCounts_Call) Return(_a0 map[string]int) *ExecutionStore_StepExecCounts_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ExecutionStore_StepExecCounts_Call) RunAndReturn(run func() map[string]int) *ExecutionStore_StepExecCounts_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: exec
func (_m *ExecutionStore) Update(exec *store.Execution) {
	_m.Called(exec)
}

// ExecutionStore_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type ExecutionStore_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - exec *store.Execution
func (_e *ExecutionStore_Expecter) Update(exec interface{}) *ExecutionStore_Update_Call {
	return &ExecutionStore_Update_Call{Call: _e.mock.On("Update", exec)}
}

func (_c *ExecutionStore_Update_Call) Run(run func(exec *store.Execution)) *ExecutionStore_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*store.Execution))
	})
	return _c
}

func (_c *ExecutionStore_Update_Call) Return() *ExecutionStore_Update_Call {
	_c.Call.Return()
	return _c
}

func (_c *ExecutionStore_Update_Call) RunAndReturn(run func(*store.Execution)) *ExecutionStore_Update_Call {
	_c.Run(run)
	return _c
}

// UpdateExecution provides a mock function with given fields: id, fn
func (_m *ExecutionStore) UpdateExecution(id string, fn func(*store.Execution)) {
	_m.Called(id, fn)
}

// ExecutionStore_UpdateExecution_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateExecution'
type ExecutionStore_UpdateExecution_Call struct {
	*mock.Call
}

// UpdateExecution is a helper method to define mock.On call
//   - id string
//   - fn func(*store.Execution)
func (_e *ExecutionStore_Expecter) UpdateExecution(id interface{}, fn interface{}) *ExecutionStore_UpdateExecution_Call {
	return &ExecutionStore_UpdateExecution_Call{Call: _e.mock.On("UpdateExecution", id, fn)}
}

func (_c *ExecutionStore_UpdateExecution_Call) Run(run func(id string, fn func(*store.Execution))) *ExecutionStore_UpdateExecution_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(func(*store.Execution)))
	})
	return _c
}

func (_c *ExecutionStore_UpdateExecution_Call) Return() *ExecutionStore_UpdateExecution_Call {
	_c.Call.Return()
	return _c
}

func (_c *ExecutionStore_UpdateExecution_Call) RunAndReturn(run func(string, func(*store.Execution))) *ExecutionStore_UpdateExecution_Call {
	_c.Run(run)
	return _c
}

// UpdateStep provides a mock function with given fields: executionID, stepID, fn
func (_m *ExecutionStore) UpdateStep(executionID string, stepID string, fn func(*runtime.StepResult)) {
	_m.Called(executionID, stepID, fn)
}

// ExecutionStore_UpdateStep_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateStep'
type ExecutionStore_UpdateStep_Call struct {
	*mock.Call
}

// UpdateStep is a helper method to define mock.On call
//   - executionID string
//   - stepID string
//   - fn func(*runtime.StepResult)
func (_e *ExecutionStore_Expecter) UpdateStep(executionID interface{}, stepID interface{}, fn interface{}) *ExecutionStore_UpdateStep_Call {
	return &ExecutionStore_UpdateStep_Call{Call: _e.mock.On("UpdateStep", executionID, stepID, fn)}
}

func (_c *ExecutionStore_UpdateStep_Call) Run(run func(executionID string, stepID string, fn func(*runtime.StepResult))) *ExecutionStore_UpdateStep_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string), args[2].(func(*runtime.StepResult)))
	})
	return _c
}

func (_c *ExecutionStore_UpdateStep_Call) Return() *ExecutionStore_UpdateStep_Call {
	_c.Call.Return()
	return _c
}

func (_c *ExecutionStore_UpdateStep_Call) RunAndReturn(run func(string, string, func(*runtime.StepResult))) *ExecutionStore_UpdateStep_Call {
	_c.Run(run)
	return _c
}

// NewExecutionStore creates a new instance of ExecutionStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewExecutionStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *ExecutionStore {
	mock := &ExecutionStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
