package action

// RegisterBuiltins registers all built-in actions.
func RegisterBuiltins(reg *Registry) {
	// Safe actions — always available
	reg.Register("set", NewSetAction)
	reg.Register("log", NewLogAction)
	reg.Register("http", NewHTTPAction)
	reg.Register("condition", NewConditionAction)
	reg.Register("loop", NewLoopAction)
	reg.Register("json.decode", NewJSONDecodeAction)
	reg.Register("json.encode", NewJSONEncodeAction)
	reg.Register("template", NewTemplateAction)
	reg.Register("delay", NewDelayAction)
	reg.Register("response", NewResponseAction)
	reg.Register("wait.webhook", NewWaitWebhookAction)
	reg.Register("wait.rabbitmq", NewWaitRabbitMQAction)
	reg.Register("rabbitmq.shovel", NewRabbitMQShovelAction)
	reg.Register("validate", NewValidateAction)
	reg.Register("lock", NewLockAction)
	reg.Register("unlock", NewUnlockAction)
	reg.Register("sql.query", NewSQLQueryAction)
	reg.Register("sql.exec", NewSQLExecAction)
	reg.Register("sql.begin", NewSQLBeginAction)
	reg.Register("sql.commit", NewSQLCommitAction)
	reg.Register("sql.rollback", NewSQLRollbackAction)
	reg.Register("schedule", NewScheduleAction)
	reg.Register("array.sort", NewArraySortAction)
	reg.Register("array.filter", NewArrayFilterAction)
	reg.Register("array.map", NewArrayMapAction)
	reg.Register("array.uniq", NewArrayUniqAction)
	reg.Register("array.pick", NewArrayPickAction)
	reg.Register("array.concat", NewArrayConcatAction)
	reg.Register("object", NewObjectAction)
	reg.Register("math", NewMathAction)
	reg.Register("hash", NewHashAction)
	reg.Register("string.replace", NewStringReplaceAction)
	reg.Register("string.match_all", NewStringMatchAllAction)
	reg.Register("table", NewTableAction)
	reg.Register("kv.get", NewKVGetAction)
	reg.Register("kv.set", NewKVSetAction)
	reg.Register("kv.delete", NewKVDeleteAction)
	reg.Register("group", NewGroupAction)

	// Powerful actions (exec, js, file.*): direct code/filesystem access,
	// blocked by the default allowlist unless the operator passes --unsafe.
	reg.Register("exec", NewExecAction)
	reg.Register("js", NewJSAction)
	reg.Register("file.read", NewFileReadAction)
	reg.Register("file.write", NewFileWriteAction)
}
