// Code generated by mockery v2.53.5. DO NOT EDIT.

package fakeaction

import (
	mock "github.com/stretchr/testify/mock"
	action "github.com/tailflow/tailflow/internal/action"
)

// Action is an autogenerated mock type for the Action type
type Action struct {
	mock.Mock
}

type Action_Expecter struct {
	mock *mock.Mock
}

func (_m *Action) EXPECT() *Action_Expecter {
	return &Action_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: ctx
func (_m *Action) Execute(ctx *action.ActionContext) (interface{}, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 interface{}
	var r1 error
	if rf, ok := ret.Get(0).(func(*action.ActionContext) (interface{}, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(*action.ActionContext) interface{}); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interface{})
		}
	}

	if rf, ok := ret.Get(1).(func(*action.ActionContext) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Action_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type Action_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - ctx *action.ActionContext
func (_e *Action_Expecter) Execute(ctx interface{}) *Action_Execute_Call {
	return &Action_Execute_Call{Call: _e.mock.On("Execute", ctx)}
}

func (_c *Action_Execute_Call) Run(run func(ctx *action.ActionContext)) *Action_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*action.ActionContext))
	})
	return _c
}

func (_c *Action_Execute_Call) Return(output interface{}, err error) *Action_Execute_Call {
	_c.Call.Return(output, err)
	return _c
}

func (_c *Action_Execute_Call) RunAndReturn(run func(*action.ActionContext) (interface{}, error)) *Action_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// Validate provides a mock function with given fields: ctx
func (_m *Action) Validate(ctx *action.ActionContext) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Validate")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*action.ActionContext) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Action_Validate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Validate'
type Action_Validate_Call struct {
	*mock.Call
}

// Validate is a helper method to define mock.On call
//   - ctx *action.ActionContext
func (_e *Action_Expecter) Validate(ctx interface{}) *Action_Validate_Call {
	return &Action_Validate_Call{Call: _e.mock.On("Validate", ctx)}
}

func (_c *Action_Validate_Call) Run(run func(ctx *action.ActionContext)) *Action_Validate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*action.ActionContext))
	})
	return _c
}

func (_c *Action_Validate_Call) Return(_a0 error) *Action_Validate_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Action_Validate_Call) RunAndReturn(run func(*action.ActionContext) error) *Action_Validate_Call {
	_c.Call.Return(run)
	return _c
}

// NewAction creates a new instance of Action. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAction(t interface {
	mock.TestingT
	Cleanup(func())
}) *Action {
	mock := &Action{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
