version: "2"
run:
  concurrency: 1
  modules-download-mode: readonly
  issues-exit-code: 2
  tests: false
  allow-parallel-runners: false
output:
  formats:
    text:
      path: stdout
      print-linter-name: true
      print-issued-lines: true
  path-prefix: ""
linters:
  default: none
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - contextcheck
    - copyloopvar
    - decorder
    - durationcheck
    - errcheck
    - errchkjson
    - errname
    - errorlint
    - exhaustive
    - ginkgolinter
    - gocheckcompilerdirectives
    - gochecknoinits
    - gochecksumtype
    - gocritic
    - godox
    - goheader
    - gomoddirectives
    - gomodguard
    - goprintffuncname
    - gosmopolitan
    - govet
    - grouper
    - importas
    - ineffassign
    - lll
    - loggercheck
    - makezero
    - mirror
    - musttag
    - nilerr
    - noctx
    - nolintlint
    - nosprintfhostport
    - perfsprint
    - prealloc
    - predeclared
    - reassign
    - revive
    - rowserrcheck
    - sloglint
    - sqlclosecheck
    - staticcheck
    - tagalign
    - testableexamples
    - testifylint
    - thelper
    - tparallel
    - unconvert
    - unparam
    - unused
    - usestdlibvars
    - usetesting
    - wastedassign
    - whitespace
    - wsl_v5
    - zerologlint
  settings:
    govet:
      disable:
        - fieldalignment
      enable-all: true
    lll:
      line-length: 140
    revive:
      confidence: 0.1
    wsl_v5:
      allow-first-in-block: true
      allow-whole-block: false
      branch-max-lines: 2
      disable:
        - decl
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - path: (.+)\.go$
        text: don't use an underscore in package name
      - path: (.+)\.go$
        text: should not use underscores in package names
    paths:
      - tmp
      - bin
      - githooks
      - tests
      - ^scripts$
issues:
  uniq-by-line: true
formatters:
  enable:
    - gofmt
    - gofumpt
    - goimports
  exclusions:
    generated: lax
    paths:
      - tmp
      - bin
      - githooks
      - tests
      - ^scripts$
